######################################################################
#
# File name : linebuffer_tb_compile.do
# Created on: Wed Apr 07 00:35:59 +0530 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../src" \
"../../../../src/lineBuffer.v" \
"../../../../sim/linebuffer_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

