######################################################################
#
# File name : linebuffer_tb_wave.do
# Created on: Tue Apr 06 13:39:16 +0530 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
