######################################################################
#
# File name : linebuffer_tb_simulate.do
# Created on: Wed Apr 07 00:36:01 +0530 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.linebuffer_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {linebuffer_tb_wave.do}

view wave
view structure
view signals

log -r /*

do {linebuffer_tb.udo}

run 12500ns
